# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://justbuchanan.com
# baseurl: /sustain/
title: Justin Buchanan
author: Justin Buchanan
description: Personal blog and resume
avatar: profile.jpg
email: justbuchanan@gmail.com
github: justbuchanan
# twitter: username
linkedin: jubuchanan
stackoverflow: users/1455275/justin-buchanan
pgp_url: https://pgp.mit.edu/pks/lookup?op=vindex&search=0x2E6E430FD8E7BDD1
#Comment out if you don't want disqus 
# disqus: username
# google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
